package ru.polardl.homeshopping.GUI;

import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import ru.polardl.homeshopping.Models.Order;
import ru.polardl.homeshopping.Models.OrderList;
import ru.polardl.homeshopping.Models.OrderPosition;

public class DetailsOfOrderForm extends javax.swing.JFrame {

    private final DefaultTableModel model;
    
    /**
     * Creates new form DetailesOfOrderForm
     */
    public DetailsOfOrderForm() {
        initComponents();
        setTitle("Order Details");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) table.getModel();
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        
        table.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        table.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
        table.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        table.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        
        
        int orderID = ShowOrdersForm.orderIDSelected;
        
        
        OrderList orderList = MainForm.orderList;
        HashMap<Integer, Order> orderListMap = orderList.getOrderListMap();
        Order order = orderListMap.get(orderID);
        

        orderIDOutput.setText(String.valueOf(orderID));
        orderDateOutput.setText(String.valueOf(order.getOrderDate()));
        discountOut.setText(String.valueOf(order.getDiscount()));
        orderStateOutput.setText(String.valueOf(order.getOrderState()));
        nameOut.setText(order.getClient().getClientName());
        addressOut.setText(order.getClient().getAddress());
        phoneOut.setText(String.valueOf(order.getClient().getPhoneNumber()));
        orderTotalPriceOut.setText(String.valueOf(order.getOrderTotalPrice()));
        
        
        HashMap<Long, OrderPosition> initialOrderPositionMap = order.getOrderPositionMap();
        TreeMap<Long, OrderPosition> sortedOrderPositionMap = new TreeMap<>();
        sortedOrderPositionMap.putAll(initialOrderPositionMap);
        
        for (Map.Entry<Long, OrderPosition> entry : sortedOrderPositionMap.entrySet()) {
            OrderPosition orderPosition = entry.getValue();
            String itemID = String.valueOf(entry.getKey());
            String name = orderPosition.getOrderPosItem().getItemName();
            String color = orderPosition.getOrderPosItem().getColor();
            String price = String.valueOf(orderPosition.getOrderPosItemFixedPrice());
            String quantity = String.valueOf(orderPosition.getOrderPosItemQuantity());
            String totalPrice = String.valueOf(orderPosition.getOrderPosTotalPrice());
            
            model.insertRow(model.getRowCount(), new Object[] {itemID, name, color, price, quantity, totalPrice});
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orderID = new javax.swing.JLabel();
        orderIDOutput = new javax.swing.JTextField();
        orderDate = new javax.swing.JLabel();
        orderDateOutput = new javax.swing.JTextField();
        client = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameOut = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        addressOut = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        phoneOut = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        orderTotalPrice = new javax.swing.JLabel();
        orderTotalPriceOut = new javax.swing.JTextField();
        discount = new javax.swing.JLabel();
        discountOut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        orderStateOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orderID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderID.setText("Order ID");

        orderIDOutput.setEditable(false);
        orderIDOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderIDOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        orderIDOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIDOutputActionPerformed(evt);
            }
        });

        orderDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderDate.setText("Order Date");

        orderDateOutput.setEditable(false);
        orderDateOutput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderDateOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        client.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        client.setText("Client:");

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name.setText("Name");

        nameOut.setEditable(false);
        nameOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        address.setText("Address");

        addressOut.setEditable(false);
        addressOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phone.setText("Phone");

        phoneOut.setEditable(false);
        phoneOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name", "Color", "Price per Item", "Quantity", "Total Item Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(110);
            table.getColumnModel().getColumn(0).setMaxWidth(110);
            table.getColumnModel().getColumn(1).setPreferredWidth(150);
            table.getColumnModel().getColumn(4).setMaxWidth(65);
        }

        orderTotalPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderTotalPrice.setText("Order Total Discount Price");

        orderTotalPriceOut.setEditable(false);
        orderTotalPriceOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderTotalPriceOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        discount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discount.setText("Discount");

        discountOut.setEditable(false);
        discountOut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        discountOut.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Order State");

        orderStateOutput.setEditable(false);
        orderStateOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderID)
                            .addComponent(orderDate))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderIDOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(orderDateOutput))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discount)
                            .addComponent(jLabel1))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(discountOut, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(orderStateOutput)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(client)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address)
                                    .addComponent(phone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addressOut, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(phoneOut)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(name)
                                .addGap(38, 38, 38)
                                .addComponent(nameOut, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderTotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderTotalPriceOut, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discount)
                        .addComponent(discountOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderID)
                        .addComponent(orderIDOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDate)
                    .addComponent(orderDateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(orderStateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client)
                    .addComponent(name)
                    .addComponent(nameOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(addressOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderTotalPrice)
                    .addComponent(orderTotalPriceOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void orderIDOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIDOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIDOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsOfOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsOfOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsOfOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsOfOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsOfOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressOut;
    private javax.swing.JLabel client;
    private javax.swing.JLabel discount;
    private javax.swing.JTextField discountOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameOut;
    private javax.swing.JLabel orderDate;
    private javax.swing.JTextField orderDateOutput;
    private javax.swing.JLabel orderID;
    private javax.swing.JTextField orderIDOutput;
    private javax.swing.JTextField orderStateOutput;
    private javax.swing.JLabel orderTotalPrice;
    private javax.swing.JTextField orderTotalPriceOut;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneOut;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
