package ru.polardl.homeshopping.GUI;

import java.util.HashMap;
import java.util.Properties;
import ru.polardl.homeshopping.Models.Config;
import ru.polardl.homeshopping.Models.Item;
import ru.polardl.homeshopping.Models.ItemList;
import ru.polardl.homeshopping.Models.OrderList;
import ru.polardl.homeshopping.Models.OrderState;

public class MainForm extends javax.swing.JFrame {

        static Properties defaultProperties = Config.getConfigProperties();
        static HashMap<Long, Item> itemListMap = ItemList.getItemListMap();
        static OrderList orderList = new OrderList();
        
        static int orderIDToChange;
    
    /**
     * Creates new form MainFrame
     */
    public MainForm() {
        initComponents();
        setTitle("Main Dialog");
        setLocationRelativeTo(null);
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createNewOrder = new javax.swing.JLabel();
        showPriceList = new javax.swing.JLabel();
        showListOfOrders = new javax.swing.JLabel();
        createNewOrderBtn = new javax.swing.JButton();
        showPriceListBtn = new javax.swing.JButton();
        showListOfOrdersBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createNewOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createNewOrder.setText("To create new Order press:");

        showPriceList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showPriceList.setText("To show Price List press:");

        showListOfOrders.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showListOfOrders.setText("To show List of Orders press:");

        createNewOrderBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        createNewOrderBtn.setText("Create Order");
        createNewOrderBtn.setPreferredSize(new java.awt.Dimension(109, 23));
        createNewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewOrderBtnActionPerformed(evt);
            }
        });

        showPriceListBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showPriceListBtn.setText("Show Price List");
        showPriceListBtn.setPreferredSize(new java.awt.Dimension(109, 23));
        showPriceListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPriceListBtnActionPerformed(evt);
            }
        });

        showListOfOrdersBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showListOfOrdersBtn.setText("Show Order List");
        showListOfOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showListOfOrdersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showPriceList)
                    .addComponent(showListOfOrders)
                    .addComponent(createNewOrder))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showListOfOrdersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showPriceListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createNewOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewOrder)
                    .addComponent(createNewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showPriceList)
                    .addComponent(showPriceListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showListOfOrders)
                    .addComponent(showListOfOrdersBtn))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showPriceListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPriceListBtnActionPerformed
        // TODO add your handling code here:
        
        new ShowPriceListForm().setVisible(true);
    }//GEN-LAST:event_showPriceListBtnActionPerformed

    private void showListOfOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showListOfOrdersBtnActionPerformed
        // TODO add your handling code here:
        
        new ShowOrdersForm().setVisible(true);
    }//GEN-LAST:event_showListOfOrdersBtnActionPerformed

    private void createNewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewOrderBtnActionPerformed
        // TODO add your handling code here:
        
        new CreateOrderForm().setVisible(true);
    }//GEN-LAST:event_createNewOrderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createNewOrder;
    private javax.swing.JButton createNewOrderBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showListOfOrders;
    private javax.swing.JButton showListOfOrdersBtn;
    private javax.swing.JLabel showPriceList;
    private javax.swing.JButton showPriceListBtn;
    // End of variables declaration//GEN-END:variables
}
