package ru.polardl.homeshopping.GUI;

import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import ru.polardl.homeshopping.Models.Order;
import ru.polardl.homeshopping.Models.OrderList;

public class ShowOrdersForm extends javax.swing.JFrame {
    
    private final DefaultTableModel model;
    static int orderIDForDetailes;
    
    //creating new instance of Order List which is not cool
    OrderList orderList = new OrderList();
    HashMap<Integer, Order> initialMap = orderList.getOrderListMap();

    /**
     * Creates new form ShowOrdersForm
     */
    public ShowOrdersForm() {
        initComponents();
        setTitle("List of Orders");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) table.getModel();
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < 5; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        
        
        //creating new instance of Order List which is not cool
//        OrderList orderList = new OrderList();
//        HashMap<Integer, Order> initial = orderList.getOrderListMap();
        
        TreeMap<Integer, Order> sorted = new TreeMap<>();
        sorted.putAll(initialMap);
        
        for (Map.Entry<Integer, Order> entry : sorted.entrySet()) {
            Order order = entry.getValue();
            String orderID = String.valueOf(entry.getKey());
            String date = String.valueOf(order.getOrderDate());
            String client = String.valueOf(order.getClient().getClientName());
            String discount = String.valueOf(order.getDiscount());
            String price = String.valueOf(order.getOrderTotalPrice());
            
            model.insertRow(model.getRowCount(), new Object[] {orderID, date, client, discount, price});
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orderScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        showDetailedInfo = new javax.swing.JLabel();
        orderIDForDetailesInput = new javax.swing.JTextField();
        showDetailedInfoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Client", "Discount", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderScrollPane1.setViewportView(table);

        showDetailedInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showDetailedInfo.setText("Show detailed info about Order ID");

        orderIDForDetailesInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        showDetailedInfoBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        showDetailedInfoBtn.setText("Show");
        showDetailedInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailedInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(showDetailedInfo)
                .addGap(42, 42, 42)
                .addComponent(orderIDForDetailesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(showDetailedInfoBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(orderScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showDetailedInfo)
                    .addComponent(orderIDForDetailesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDetailedInfoBtn))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDetailedInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDetailedInfoBtnActionPerformed
        // TODO add your handling code here:
        
        try {
            orderIDForDetailes = Integer.parseInt(orderIDForDetailesInput.getText());
            if (orderIDForDetailes <= 0) {
                WrongInputForm.wrongInputMassage = "Order ID can't be 0 or less. Check input";
                new WrongInputForm().setVisible(true);

//                System.out.println("Order ID can't be 0 or less");
            } else if (initialMap.containsKey(orderIDForDetailes)) {
                new DetailsOfOrderForm().setVisible(true);
            } else {
                WrongInputForm.wrongInputMassage = "No Order with this ID in List of Orders. Check input";
                new WrongInputForm().setVisible(true);
            }
        } catch (Exception e) {
            WrongInputForm.wrongInputMassage = "Order ID must be an uninterrupted sequence of numbers. Check input";
            new WrongInputForm().setVisible(true);
            
//            System.out.println("Order ID is Integer. Check input");
        }      
    }//GEN-LAST:event_showDetailedInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowOrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowOrdersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderIDForDetailesInput;
    private javax.swing.JScrollPane orderScrollPane1;
    private javax.swing.JLabel showDetailedInfo;
    private javax.swing.JButton showDetailedInfoBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
